winget install --id=Discord.Discord -e ;
winget install --id=Microsoft.VisualStudioCode -e ;
winget install --id=Bitwarden.Bitwarden -e ;
winget install --id=Telegram.TelegramDesktop -e ;
winget install --id=Notepad++.Notepad++ -e ;
winget install --id=Nvidia.GeForceExperience -e ;
winget install --id=voidtools.EverythingLite -e ;
winget install --id=Microsoft.PowerShell -e ;
winget install --id=ProtonVPN.ProtonVPN -e ;
winget install --id=Google.Chrome -e ;
winget install --id=Deezer.Deezer -e
