import = [
  "~/.config/alacritty/tokyonight_day.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_title = false
startup_mode = "maximized"

[font]
size = 14
normal.family = "CaskaydiaCove Nerd Font"

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
	{ key = "Space", mods = "Control", chars = "\u0000" }
]
